language: python

cache: pip
env:
    - TOXENV=py27
    - TOXENV=py33
    - TOXENV=py34
    - TOXENV=py35
    - TOXENV=pypy
    - TOXENV=pep8
before_install:
    - pip install --upgrade pip setuptools
install:
    - pip install tox
    - if [ "$TOXENV" = 'py34' ]; then pip install coveralls; fi
script:
    - tox -e $TOXENV
after_success:
    - if [ "$TOXENV" = 'py34' ]; then coveralls; fi
