language: python

python:
    - "3.5"
    - "3.6"
    - "3.7"
    - "3.8"
    - "pypy3.6-7.1.1"
matrix:
  include:
    - python: 3.5
      env: TOXENV=py35-nocrypto
    - python: 3.6
      env: TOXENV=py36-nocrypto
    - python: 3.7
      env: TOXENV=py37-nocrypto
    - python: 3.8
      env: TOXENV=py38-nocrypto
    - python: pypy3.6-7.1.1
      env: TOXENV=pypy3-nocrypto
    - python: 3.5
      env: TOXENV=py35-crypto
    - python: 3.6
      env: TOXENV=py36-crypto
    - python: 3.7
      env: TOXENV=py37-crypto
    - python: 3.8
      env: TOXENV=py38-crypto
    - python: pypy3.6-7.1.1
      env: TOXENV=pypy3-crypto
    - python: 3.7
      env: TOXENV=pep8
    - python: 3.7
      env: TOXENV=coverage

before_install:
    - pip install --upgrade pip setuptools
install:
    - pip install tox
script:
    - tox -s false -e $TOXENV
