language: python

matrix:
  include:
    - python: 2.7
      env: TOXENV=py27-nocrypto
    - python: 3.4
      env: TOXENV=py34-nocrypto
    - python: 3.5
      env: TOXENV=py35-nocrypto
    - python: 3.6
      env: TOXENV=py36-nocrypto
    - python: 2.7
      env: TOXENV=py27-crypto
    - python: 3.4
      env: TOXENV=py34-crypto
    - python: 3.5
      env: TOXENV=py35-crypto
    - python: 3.6
      env: TOXENV=py36-crypto
    - python: 3.5
      env: TOXENV=pep8
    - python: 3.5
      env: TOXENV=coverage

before_install:
    - pip install --upgrade pip setuptools
install:
    - pip install tox
script:
    - tox -e $TOXENV
